### ISSUE TITLE
Rotation issue with Iphone-photos from google photos

### ISSUE THREAD

**Issue by filipclaeys** [nanostudio-org/nanogallery2#41] opened 2017-04-20 17:04 UTC
I have an issue with portrait photo's taken with an Iphone ans stored on google photo's. The thumbnails are displayed correct, but the large photo's are displayed landscape.

**Comment by Kris-B** [comment] 2017-04-21 12:09
are the large photos displayed correctly in google photos?
do you have page where I could check this issue?

**Comment by filipclaeys** [comment] 2017-04-21 12:30
In Google they are displayed correctly.
You can check it on http://www.ksaahoyvinkt.be/fotos-google.html.
Thanks!

**Comment by Kris-B** [comment] 2017-05-03 11:34
The image retrieved via Google Photos API are not correctly oriented.
The orientation is not provided in the API data.

The EXIF data of the image contains the correct orientation, but these data are only available when the image is fully downloaded. It would be necessary to remove the progressive image display and wait until the end of the download to display an image, which is not acceptable.

A this time I don't have any solution for your problem, so I'm closing this issue.

**Comment by wuhi** [comment] 2018-05-23 07:05
i got a woraround for this.
the problem is that google delivers the origin images. so the image is as it is with all the maybe wrong exif from the camera.
if you replace the Google.url() parameter &imgmax=d with &imgmax=720 google will generate a newly rendered image that has correct orientation.
valid values for imgmax are 94, 110, 128, 200, 220, 288, 320, 400, 512, 576, 640, 720, 800, 912, 1024, 1152, 1280, 1440, 1600
https://developers.google.com/picasa-web/docs/3.0/reference#Parameters

**Comment by tenuki** [comment] 2018-08-19 03:41
@Kris-B i'm having I think the same "issue" with flickr, although I'm using its links by my own and not the flickr gallery from nanogallery2 ( [example in codepen](https://www.instagram.com/yellowblockbnbnyc/) ).

I think it happens only with the "original" version of photo, in which, exif data says in "which" orientation it was taken, and it is up to the software to display it properly (*).

I do understand what you say above about fixing it, and it just seems a corner case:
 *  having an original photo with this data
 * & wanting to not pre - process it before upload
 * & also wanting to display it that original resolution which maybe kind of odd..

However I think that same problem would happen for some lower resolution image which may have the exif data associated to it and which would load fast enough to not to worry about "progressive" display.. in which you can read its exif information fast too.

(*) Only in original, as other versions of pictures are generated, then will be generated directly in vertical orientation. Interestly enough when you open such an image in browsers in a direct way ( I mean open the image url in the browser) it is displayed with right rotation. However if you put it linked from an html it isn't rotated. Also only firefox seems to support style: img { image-orientation: from-image; } .
Some people finally ends up doing after loading processing with exif-js and applying custom css rotation like this:

    EXIF.getData(imageElement, function() {
                var orientation = EXIF.getTag(this, "Orientation");
                if(orientation == 6)
                    $(imageElement).css('transform', 'rotate(90deg)')
    });  

or something like that (I've used 270deg with orientation 8). Check more about this [here](https://stackoverflow.com/questions/24658365/img-tag-displays-wrong-orientation).

**Comment by tenuki** [comment] 2018-08-19 03:52
If it is not directly supported by nanogallery2 it maybe useful to be able to have a few options.. if possible, like:
 1.  maybe allow to manually specify rotation where image is specified (the <a> tag).  I don't really like it being not automatic but it would be an intermediate solution and you don't have to wait image to be loaded to know you have to rotate it.
 2. it would be nice to be able to implement something like that with the callbacks but I'm not really sure it is possible right now (or my efforts wasn't enough).  I was trying something like this (assuming the thumbnail is taking from the same full image etc..) but wasn't nice nor good and don't think it would be enough if you use an actual thumbnail instead the real image: 

<pre>
    var my_all = {};
    var my_all2 = {};
    function fnThumbnailInit (thumbnail, item, GOMidx) {
           var imgg = $(thumbnail[0]).find("img").get()[0];
           console.log("3>", imgg.currentSrc, my_all[imgg.currentSrc]);
          my_all[imgg.currentSrc] = "done";
          my_all2[imgg.currentSrc] = $(thumbnail[0]).find(".nGY2TnImg").get();
          // $(thumbnail[0]).find(".nGY2TnImg").addClass("rotate90");
    }

      function fnDemopProcessData(item, kind, sourceData) {
          // console.log("item:", item);
          // console.log("itemXX>", item.thumbs.url['l1']['xs']);
          //  console.log("1after 1..", sourceData.href);
               try {
                   window.EXIF.getData(item, function () {
                      var orientation = EXIF.getTag(this, "Orientation");
                      console.log("orientation:", orientation);
                       var key = item.thumbs.url['l1']['xs'];
                      $(my_all2[key]).addClass("rotate90");
                  });
               } catch(err) {
               }
        };
</pre>

 3. this rotation issue me also happen to thumbnails... 

which would be the way to go?

**Comment by Kris-B** [comment] 2019-03-11 13:33
I'm closing this issue because this is dependant from an external data provider, which, by definition, I cannot manage.

**Closed by Kris-B** 2019-03-11 13:33 UTC

**Comment by tenuki** [comment] 2019-03-11 17:19
> I'm closing this issue because this is dependant from an external data provider, which, by definition, I cannot manage.

Same happens when you provide images yourself.
