### ISSUE TITLE
Duplication of galleries when rendering many of them

### ISSUE THREAD

**Issue by rsieja** [nanostudio-org/nanogallery2#50] opened 2017-06-16 19:31 UTC
My homepage ( http://rodrigosieja.com.br/index_old.html ) has 4 galleries. Some gallery or galleries will appear randomly - either of the wrong "section", or repeating itself on the other sections.

The occurrence is random, mostly when scrolling down before the page is fully loaded.

Screenshot:

![2017-06-17 11_29_42-fotografia - rodrigo sieja](https://user-images.githubusercontent.com/5354958/27253731-50ff3f16-5350-11e7-8379-a2adf0d1cbb9.png)

**Comment by Kris-B** [comment] 2017-06-20 15:32
I could not reproduce this issue, but:
- please add an unique `ID` to each gallery container
- I detected a small bug (which does not impact the issue): please use `album` instead of `photoset` (will be fixed in the next release)
- are you using bLazy.JS to lazy load images in nanogallery2?

**Comment by rsieja** [comment] 2017-06-20 17:08
Yes, I'm using bLazy. They already have unique ids, so maybe bLazy is messing it all. I'll try using `album`, coming back soon.

**Comment by rsieja** [comment] 2017-06-20 17:23
Oops, the `div`s didn't have unique IDs (despite different code in `data-nanogallery2`). That was exactly the issue. And I can use bLazy.

**Comment by Kris-B** [comment] 2017-06-20 21:09
;-)

**Closed by Kris-B** 2017-06-20 21:09 UTC

**Comment by Kris-B** [comment] 2017-06-20 21:13
BTW: nanogallery2 implements natively lazy load, so not sure that bLazy is really useful....
