### ISSUE TITLE
Crash when destroying and re-initializing gallery

### ISSUE THREAD

**Issue by JonMerlevede** [nanostudio-org/nanogallery2#56] opened 2017-07-01 01:33 UTC
When I destroy a gallery (using `nanogallery2('destroy')`) and then create a new gallery in the same DOM element, nanogallery makes the browser hang. Using the same code with nanogallery2 v1.3 I get the intended behavior.

**Comment by Kris-B** [comment] 2017-07-01 21:18
I'm using this on the showcase page without any problem (http://nanogallery2.nanostudio.org/demonstration.html)

Can you please provide your code?

**Comment by JonMerlevede** [comment] 2017-07-02 13:10
Yeah sure! It's not the best code, but since it works with v1.3 I didn't investigate too much (｡･_･｡).
You can find an example gallery here: https://acd.5ha.re/a/NtI6DiuWmENEk64ivtyqfFX0I23F4OaI6iI3qXQQRxQ

The problem occurs when clicking the toggle button and then opening an image. Here it works, but when replacing with version 1.4 the browser hangs instead.

**Comment by Kris-B** [comment] 2017-07-06 21:08
I'm getting the error "{"logref":"66214796-628c-11e7-9b37-656ba96d150c","message":"ShareId does not exists"}" when trying your page...

Could you please create a codepen ?

**Comment by andradobritoiu** [comment] 2017-07-24 15:12
I have the same issue with nanogallery2 v1.4, destroying then re-initializing the gallery getting this error: Cannot read property 'contentLength' of null
    at Function.window.NGY2Item.NGY2Item.New

**Comment by Kris-B** [comment] 2017-07-24 16:07
any page online where I can test this?
thanks

**Comment by Kris-B** [comment] 2017-07-25 10:32
I cannot reproduce this issue... a full working codepen would be very helpful. thanks!

**Comment by JonMerlevede** [comment] 2017-10-12 15:32
Sorry for leaving this unanswered for such an embarrassingly long time. I tried this, but the problem is that when I copy+paste my code verbatim into a Codepen, the problem does not occur! Then I kind of forgot about it 😨 .

Anyway; in the new version (1.5) there is no longer a crash. Now, after re-initializing the gallery, the image is just not displayed. I do not get why you get the error "ShareId does not exist"; for me the link that I sent you is still working fine. I spent some time now trying to figure out what the difference is between the Codepen and my own code, but I cannot seem to figure it out :/.

You should still be able to observe the problem on this page: https://acd.5ha.re/a2/NtI6DiuWmENEk64ivtyqfFX0I23F4OaI6iI3qXQQRxQ. The problem occurs when clicking the toggle button and then open an image.
This Codepen contains exactly the same code, but does work: https://codepen.io/JonMerlevede/pen/gGjvWZ. Just to make sure that I was actually using the same code, the Javascript is even loading from the same place as on the website above.
The code also works when I load it into a Javascript Fiddle...

I'm really stumped.

You should be able to check the same gallery running v1.3, working, on https://acd.5ha.re/a/NtI6DiuWmENEk64ivtyqfFX0I23F4OaI6iI3qXQQRxQ.

**Comment by Kris-B** [comment] 2017-11-06 21:48
maybe you could check the latest beta version: https://github.com/nanostudio-org/nanogallery2/tree/dev

**Comment by JonMerlevede** [comment] 2017-11-06 22:21
My problem is fixed in the latest dev version, thanks!

**Comment by Kris-B** [comment] 2017-11-06 22:24
thanks for the update!
it's still beta, some features may be unstable...

**Comment by Kris-B** [comment] 2017-12-01 08:40
final version released: https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.0.0

**Comment by Kris-B** [comment] 2017-12-04 20:57
I'm closing this issue, for now, open it again if it's not fixed for you

**Closed by Kris-B** 2017-12-04 20:57 UTC
